- name: Remove alacritty
  become: true
  file:
    path: /usr/local/bin/alacritty
    state: absent
  tags:
    - alacritty

- name: Cloning alacritty
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "{{ lookup('env', 'HOME') }}/alacritty"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - alacritty

- name: Build alacritty
  shell: ". {{ lookup('env', 'HOME') }}/.cargo/env && cd {{ lookup('env', 'HOME') }}/alacritty && cargo build --release"
  tags:
    - alacritty

- name: Create a Symlink
  shell: "{{ item }}"
  with_items:
    - "cd {{ lookup('env', 'HOME') }}/alacritty && cp target/release/alacritty /usr/local/bin"
    - "cd {{ lookup('env', 'HOME') }}/alacritty && cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg"
  tags:
    - alacritty
