- name: Install System Packages 1
  become: true
  with_items:
    - cmake
    - pkg-config
    - python3
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  tags:
    - server
    - install
    - neovim
    - core
    - alacritty

- name: Install System Packages 2
  become: true
  with_items:
    - lua
    - unzip
    - libtool
    - gettext
    - fzf
    - wget
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  tags:
    - server
    - install
    - neovim
    - core
    - bun

- name: Install System Packages 3
  become: true
  with_items:
    - curl
    - htop
    - lsof
    - ccache
    - moreutils
    - rust
    - go
    - neovim
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  tags:
    - install
    - core
