- name: Installing stow
  become: true
  ansible.builtin.pacman:
    name: 'stow'
    state: present
  tags:
    - server
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/azatakmyradov/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    version: main
  tags:
    - server
    - install
    - dotfiles
    - stow

- name: Create directory if not exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
    mode: '0755'
  tags:
    - server
    - install
    - dotfiles
    - stow

- name: Clone neovim config
  ansible.builtin.git:
    repo: 'https://github.com/azatakmyradov/kickstart.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    recursive: true
    update: true
    version: main
  tags:
    - server
    - install
    - dotfiles
    - neovim
    - stow

- name: Stow dotfiles
  ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/.dotfiles && ./install"
  changed_when: false
  tags:
    - server
    - install
    - dotfiles
    - stow
