# Block 1: Node.js and npm Installation
- name: Ensure Node.js and npm are installed
  become: true
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm
  tags:
    - node

# Block 2: Global npm Packages Installation
- name: Install global npm packages
  become: true
  ansible.builtin.npm:
    name: "{{ item }}"
    global: true
  loop:
    - eslint
    - typescript
    - typescript-language-server
    - ts-node
  tags:
    - node
