- name: Install Node.js and npm
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm
  tags:
    - node
    - install

- name: Install n (Node.js version manager)
  become: true
  npm:
    name: n
    global: yes
  tags:
    - node
    - install

- name: Install LTS version of Node.js using n
  become: true
  command: n lts
  tags:
    - node
    - install
