- name: Install Yarn
  become: true
  npm:
    name: "{{ item }}"
    global: yes
  loop:
    - yarn
    - eslint
    - typescript-language-server
    - typescript
    - ts-node
  tags:
    - install
    - node
