- name: Install Yarn
  become: true
  ansible.builtin.npm:
    name: "{{ item }}"
    global: true
  loop:
    - eslint
    - typescript-language-server
    - typescript
    - ts-node
  tags:
    - server
    - install
    - node
