- name: Table Plus
  become: true
  ansible.builtin.git:
    repo: https://aur.archlinux.org/tableplus.git
    dest: "{{ lookup('env', 'HOME') }}/src/tableplus"
    version: master
  tags:
    - tableplus
    - install
    - productivity

- name: Install packages
  become: true
  ansible.builtin.pacman:
    name:
      - "tmux"
      - "fzf"
      - "xclip"
      - "tldr"
      - "ripgrep"
      - "i3"
  tags:
    - install
    - productivity
