- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_dir }}"
    mode: "0700"
    state: directory
  tags:
    - server
    - dotfiles
    - install
    - ssh

- name: Install ssh keys
  copy:
    src: "{{ item.source }}"
    dest: "{{ ssh_dir }}/{{ item.name }}"
    mode: "0600"
  loop: "{{ ssh_keys }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - server
    - dotfiles
    - install
    - ssh

- name: Install ssh public keys
  copy:
    src: "{{ item.source }}.pub"
    dest: "{{ ssh_dir }}/{{ item.name }}.pub"
    mode: "0644"
  loop: "{{ ssh_keys }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - server
    - dotfiles
    - install
    - ssh

- name: Add SSH public keys to authorized_keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', item.source + '.pub') }}"
  loop: "{{ ssh_keys }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - server
    - dotfiles
    - install
    - ssh
