- name: Ensure ZSH shell is installed
  become: true
  ansible.builtin.pacman:
    name: 'zsh'
    state: present
  tags:
    - shell

- name: Change default shell to ZSH for the current user
  changed_when: false
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  tags:
    - shell

- name: Install Starship prompt
  ansible.builtin.shell: |
    set -o pipefail
    curl -sS https://starship.rs/install.sh | sh -s -- -y
  changed_when: false
  tags:
    - shell

- name: Clone zsh-autosuggestions plugin from GitHub
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.zsh/zsh-autosuggestions"
    version: master
  tags:
    - shell
