- name: Install ZSH
  become: true
  ansible.builtin.pacman:
    name: 'zsh'
    state: present
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh', 'server']

- name: Change shell to zsh
  changed_when: false
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Install Starship
  ansible.builtin.shell: |
    set -o pipefail
    curl -sS https://starship.rs/install.sh | sh -s -- -y
  changed_when: false
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.zsh/zsh-autosuggestions"
    version: master
  tags: *tags_for_zsh_tasks
