- name: Install ZSH
  become: true
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh', 'server' ]

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  tags: *tags_for_zsh_tasks
  become_user: "{{ user }}"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.zsh/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
